### ISSUE TITLE
thread hatası

### ISSUE THREAD

**Issue by hakancelik96** [hakancelik96/filop#4]
```python

class Filop():
    """ python dosya işlemleri, ana sınıf bu """
    def __init__(self,scan = False,year = 0,month = 0,day = 5):
        """scan false demek program baştan sona tüm pc yi taramak yerine daha önceden depolamış olduğu veritabanından
        bilgiyi alıp öyle arama yapacak,eğer daha önce kayıt etmemişse tarayıp kayıt edecek ve filop sınıfına girilmiş olanlar
        parametrelerdeki tarhi geçmiş ise son kayıt tarihi tekrar tarayıp depolayacak,
        eğer veri tabanı ile hiç uğraşmamak için veya yeni bir dosya arıyolar ise scan True yapılmalı"""
        self.all_folders=[] # bu pc de ki tüm klasör lerin listesidir
        self.scan = scan
        self.year = year
        self.month = month
        self.day = day
        if self.scan == False: # eğer True olursa işlemler veritabanına bağlanmadan canlı olarak yapılır
            self.s = s
            try:
                last_save = str(self.s.query(Folders).order_by(Folders.id)[0].time).split()[0].split("-")
                now = str(strftime("%Y-%m-%d", gmtime())).split("-")
                int(now[0])-int(last_save[0]) > self.year and int(now[1])-int(last_save[1])\
                > self.month and int(now[2])-int(last_save[2]) > self.day
                scan_is = False
            except IndexError:
                scan_is = True
            if scan_is:
                print("""güncel veriler kayıt ediliyor bu yüzden biraz zaman alabilir,
                          işlem bittikden sonra arama işlemleriniz daha hızlı olacaktır
                           --
                           The current data is saved so it can take some time and it will process faster after the process is finished""")
                try:
                    os.remove(settings.db_name) # eski db yi siliyorum
                except:
                    pass
                self.scan = True # bunu böyle yapıyorum ki anlık tarayıp verileri kayıt etsin
                for i in self.isdir(): # bütün klasörleri ekliyorum
                     data = Folders(path=i)
                     self.s.add(data)
                for i in self.searchfile(""): # bütün dosyaları ekliyorum
                    data = Files(path=i)
                    self.s.add(data)
                self.s.commit() # ve kayıt ettim
                self.scan = False # ve tekrar eski haline gelir

    def isdir(self): # pc deki tüm klasörleri bulan fonksiyon
        if self.scan == False:
            for isd in self.s.query(Folders).order_by(Folders.id):
                yield isd.path
        else:
            self.thread(self.isdir_driver,[i for i in self.drivers()])
            self.thread(self.isdir_allfolder,self.all_folders)


    def isdir_driver(self,driving):
        for i in Help(driving).folder():
            if i not in self.all_folders:
                 self.all_folders.append(i)
                 yield i

    def isdir_allfolder(self,folder):
        for fo in Help(isd).folder():
            if fo not in self.all_folders:
                self.all_folders.append(fo)
                yield fo


    def drivers(self): # ve pc de kullanılan sürücü yollarını buluyoruz
        extensions="qwertyuıopğüişlkjhgfdsazxcvbnmöç/"
        for ex in extensions:
            try:
                os.listdir(str(ex)+":")
                yield str(ex)+":"+os.sep
            except:
                pass

    def searchfile(self,word,type_=None): # aranan kelime ile işlesen dosya isimlerini bulur
        if self.scan == False:
            for isd in self.s.query(Files).order_by(Files.id):
                # type_ olayı yok burda eklenmesi gerek
                isd_list = []# search de çalışabilmesi için liste yaptım
                isd = isd.path
                if type_!=None: # None değil ise dosya türü istiyordur
                    if type(list(type_))==type(type_): # liste olarak belirli türleri isteyebilir
                        for pat in type_:
                            if isd.endswith("."+pat):
                                isd_list.append(full_ex)
                    elif type(str(type_))==type(type_):
                        if isd.endswith("."+type_):
                            isd_list.append(isd)
                else:
                    isd_list.append(isd)
                for add in Search(word,isd_list).match:
                    yield add
        else:
            for isd in self.isdir() :
                for add in Search(word,Help(driv=isd).file(type_=type_)).match:
                    yield add

    def searchfolder(self,word): # aranan kelime mile eşleşen dosyaları bulur
        if self.scan == False:
            for isd in self.s.query(Folders).order_by(Folders.id):
                isd_list = []
                isd_list.append(isd.path)
                # type_ olayı yok burda eklenmesi gerek
                for add in Search(word,isd_list).match:
                    yield add
        else:
            for isd in self.isdir():
                for add in Search(word,Help(driv=isd).folder()).match: # burda bir kod ve işlem fazlalığı varmış gibi geliyor ama
                # kodu düzeltince sonuç alınmıyor anlamadım
                    yield add

    def open(self,path): # list or str girilen yoldaki dosya yı açar liste veya str olarak girilebilir
        liste=[]
        if type(liste)==type(path):
            for pat in path:
                os.startfile(pat)
        else:
            os.startfile(path)

    def size(self,path):
        if type(list(path))==type(path): # liste olarak girilmiş ise
            show=[]
            for pat in path:
                if os.path.isdir(pat): # klasör ise
                    total_size=0
                    for f in Help(driv=pat).file():
                        total_size+=os.stat(f).st_size
                    for fo in Help(driv=pat).folder(): # altındaki tüm klasörleri buluyoruz
                        for f in Help(driv=fo).file():
                            total_size+=os.stat(f).st_size
                    show.append(Help(driv=pat).size(totaly=total_size))
                else: # dosya ise
                    for pat in path:
                        try:
                            show.append(Help(driv=pat).size())
                        except:
                            pass
            return show
        elif type(str(path))==type(path): # sadece bir tane str olarak girilmiş ise
            if os.path.isfile(path): # dosya ise
                return Help(driv=path).size()
            else: # klasör ise
                total_size=0
                show=[]
                for f in Help(driv=path).file():
                    total_size+=os.stat(f).st_size
                for fo in Help(driv=pat).folder(): # altındaki tüm klasörleri buluyoruz
                    for f in Help(driv=fo).file():
                        total_size+=os.stat(f).st_size
                show.append(Help(driv=pat).size(totaly=total_size))
                return show
        else:
            return "You should only use list or str" # buraya düzgün bir hata olayı yap

    def thread(self,target,th):
        """
        targe hedef fonksiyondur,
        th ise bir listedir ve bu listenin öğelerini target e yazılan fonksiyon içine atılarak her öğe için
        bir tane thread oluşturulur
        ---
        aynı anda birden fazla iş yapmak için ,
        bu cpu kullanım oranını arttıran bir fonksiyondur,
        örnek olarak, bulunan her klasör yolu içini tek tek taramak yerine,
        bu fonksiyon sayesinde her klasör yolu nu aynı anda tarayıp daha hızlı sonuç olmak mumkün"""
        th2 = []   # empty list is created
        for t in th:
            thread = Thread(target=target, args=(t))
            thread.start()
            th2.append(thread)
        for t in th2:
            t.join()
```

**Comment by hakancelik96** [comment]
arama işlemlerini hızlandırmak adına thread kullanmak istedim kodlara yerleştirdim bunun içn filop sınıfı içerisine thread adında fonksiyon olarak yazdım ve isdir fonksiyonunda birden fazla arama yapmak için  isdir_driver ve isdir_allfolder olarak parçaladım ve isdir fonksiyonda thread fonksiyonunu çağırdım ama çalışmadı ve verdiği hata şu şekilde 

```python
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\python\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\python\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
TypeError: isdir_driver() takes 2 positional arguments but 4 were given

Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\python\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\python\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
TypeError: isdir_driver() takes 2 positional arguments but 4 were given
```

**Comment by hakancelik96** [comment]
galiba hatanın sebebi  [i for i in self.drivers()] bu kod d:\\  ve c:\\ şeklinde geliyor ve her biri 4 karakter ve bu nedenle 4 tane arguman verdim saniyor bunu nasıl düzeltirim ?
